Fix error handling/messages.

diff --git a/bin/gw b/bin/gw
--- a/bin/gw
+++ b/bin/gw
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [[ -z "$2" ]]; then
-    echo "$0: usage: gw <grep-pattern> <letter-tile-list>"
+    echo "$0: usage: gw <grep-pattern> <letter-tile-list>" 1>&2
     exit 1
 fi
 
@@ -11,14 +11,16 @@ lists=(/usr/share/dict/american-english-huge \
         /usr/share/dict/american-english-large \
         /etc/dictionaries-common/words)
 
+found=0
 for f in ${lists[@]}; do
     if [[ -e "$f" ]]; then
+        found=1
         break
     fi
 done
 
-if [[ -z "$f" ]]; then
-    echo "$0: failed to find any of: (${lists[@]})"
+if [[ $found -eq 0 ]]; then
+    echo "$0: failed to find any of: (${lists[@]})" 1>&2
     exit 1
 fi
 
